In [1]:
!pip install numpy

In [ ]:
import numpy as np #importing numpy ,## import is keyword , as is alias , np is alias
print (np.__version__)


2.3.1


In [3]:
lst = [1,2,3,4,5,5]
print(lst)
print("type of lst:-",type(lst))


[1, 2, 3, 4, 5, 5]
type of lst:- <class 'list'>


In [4]:
arr = np.array(lst)
print(arr)
print("type of array:-",type(arr))


[1 2 3 4 5 5]
type of array:- <class 'numpy.ndarray'>


In [6]:
lst= list(range(1,10))
print(type(lst))
arr=np.array(lst)
arr

<class 'list'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
# np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# arr = np.arange(1,31)
# arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
# arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
# arr.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
# arr=np.random.randint(1,5,9)
# arr


array([3, 3, 4, 4, 2, 3, 2, 4, 2], dtype=int32)

In [33]:
 arr=np.random.randint(1,5,(5,2))
 arr

array([[2, 4],
       [4, 3],
       [1, 1],
       [1, 2],
       [1, 1]], dtype=int32)

In [34]:
np.random.random((5,2))

array([[0.97892834, 0.08362519],
       [0.82763346, 0.99710654],
       [0.50665474, 0.73621135],
       [0.65540914, 0.19574887],
       [0.12302807, 0.45787305]])

In [38]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [39]:
print("array shape:-",arr.shape)
print("size of array:-",arr.size)
print("number of dim:-",arr.ndim)
print("dtype of array:=",arr.dtype)

array shape:- (12, 5)
size of array:- 60
number of dim:- 2
dtype of array:= int64


In [ ]:
arr.flatten() #2-D convert into 1-D.


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [43]:
arr.ravel() # to show.
print("array shape:-",arr.shape)
print("size of array:-",arr.size)
print("number of dim:-",arr.ndim)
print("dtype of array:=",arr.dtype)

array shape:- (12, 5)
size of array:- 60
number of dim:- 2
dtype of array:= int64


In [51]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [52]:
arr[11][4]

np.int64(59)

In [53]:
arr[11][-1]

np.int64(59)

In [55]:
arr[11:12,4]

array([59])

In [57]:
arr[11:12,-1]

array([59])

In [60]:
arr[-1][-1]=100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [94]:
# min. max. mine. TASK

In [47]:
arr.T.shape


(5, 12)

In [48]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [68]:
arr=np.arange(225).reshape(5,15,3)
arr


array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [67]:
print("array shape:-",arr.shape)
print("size of array:-",arr.size)
print("number of dim:-",arr.ndim)
print("dtype of array:=",arr.dtype)

array shape:- (5, 15, 3)
size of array:- 225
number of dim:- 3
dtype of array:= int64


In [ ]:
arr[0] #1st table

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [ ]:
arr[0][0] #1st row of 1st table

array([0, 1, 2])

In [ ]:
arr[0][0][0] # is element of ist row of 1st table

np.int64(0)

In [73]:
arr[0:2,1:3,1:3]

array([[[ 4,  5],
        [ 7,  8]],

       [[49, 50],
        [52, 53]]])

In [76]:
arr[0]
arr[1]


array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [80]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [96]:
# arr1+arr2
# arr1*arr2
# arr1+2               TASK
# arr1/arr2

In [91]:
arr=np.array([5,1,9,3])
print(np.min(arr))

1


In [92]:
arr=np.array([5,1,9,3])
print(np.max(arr))

9


In [93]:
arr=np.array([5,1,9,3])
print(np.mean(arr))

4.5
